<?php
/**
 * Advanced Custom Fields configuration
 *
 * This file can be regenerated by going to Custom Fields > Export, selecting all field sets, and clicking "Export to PHP".
 *
 * It's important to keep this file synchronized with the XML export for the sake of future development.
 * For a further explanation of this feature/workflow, please see the following blog post:
 * @link http://stevegrunwell.com/blog/exploring-the-wordpress-advanced-custom-fields-export-feature/
 *
 * @package %Theme_Name%
 * @author %Author%
 */

// Paste your ACF PHP export here